name: External projects test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-combinations:
      name: Create project combinations
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install locally
        run: python3 -m pip install -e .

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: list all test sessions
        id: set-matrix
        run: echo "::set-output name=matrix::$(opp_env list --flat | grep -P '^(?!(omnetpp|inet|simulte|simu5g|veins))')"

      # save the list into the outputs
      outputs:
        matrix: ${{ toJson(steps.set-matrix.outputs.matrix) }}

  smoketests:
    needs: create-combinations
    strategy:
      fail-fast: false
      matrix:
        projects: ${{ fromJson(needs.create-combinations.outputs.matrix) }}
    name: Smoke test # ${{ matrix.projects }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install locally
      run: python3 -m pip install -e .

    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    # - name: 'run smoke test'
    #   working-directory: tests
    #   run: ./project_tester --dry-run install ${{ matrix.projects }}

    - name: display matrix
      run: echo "${{ matrix.projects }}"

    # - name: Show output
    #   if: always()
    #   run: |
    #     echo "::group::Output"
    #     cat tests/out.txt || echo '(no output)'
    #     echo "::endgroup::"

    #     echo "::group::Cumulative output"
    #     cat tests/cumulative_out.txt || echo '(no output)'
    #     echo "::endgroup::"
